apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::971326070093:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10WGL927EZDGT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::971326070093:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-10T18:45:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1775"
  uid: 812ec1ac-09e2-42c1-8446-178fb5fd84bb
